### ISSUE TITLE
Add a button to switch to/from dark mode

### ISSUE THREAD

**Issue by Binnette** [unbezahlbar/unbezahlbar.github.io#33]
Hello, my windows computer is configured to be in dark mode. So the map always show in dark mode.

And sadly, the dark mode need more love to be more readable:

![image](https://user-images.githubusercontent.com/6597721/162799405-1c41c9fd-1a98-4459-8ff1-e276f9bd0303.png)

That's why we need a button to allow users to switch from dark mode to light mode. To make the "priceless map" beautiful and readable again ❤️

**Comment by ToastHawaii** [comment]
Switching between dark, light and system mode is now supported. :)
![image](https://user-images.githubusercontent.com/1504145/202018324-3ccbe584-26f7-44f0-b97a-c9fee13fbd38.png)
